# Team members
Name: Harsh Agarwal
Matrikelnummer: 7024725
email: haag00001@stud.uni-saarland.de

Name: Zurana Mehrin Ruhi
Matrikelnummer: 7023892
email: zuru00001@stud.uni-saarland.de

# Exercise 5.4 (4 points)
### **Do not edit this notebook**
Implement the __call__() method in every activation function. You don't have to implement backward() anywhere for now.

In [1]:
import numpy as np

In [2]:
from activations import ReLU, LeakyReLU, Tanh, Softmax, Sigmoid
from losses import CrossEntropy, MSELoss
from layers import Linear

## Ex5.4 a Implement ReLU() activation function (0.5 point)
Implement the __call__ function in ./activations/ReLU.py which takes a tensor x as input and applies the ReLU activation function on x. 

f(x) = max(0,x)

In [3]:
relu = ReLU()
x = np.array([0.1, -0.3, 0.5, 0.9, 0, -1.0])
relu(x)

array([0.1, 0. , 0.5, 0.9, 0. , 0. ])

## Ex5.4 b Implement LeakyReLU() activation function (0.5 point)
Implement the __call__ function in ./activations/LeakyReLU.py which takes a tensor x as input and applies the LeakyReLU activation function on x.

$f(x) = \alpha x \text{ if } x < 0$    
$f(x) =   x \text{ if } x \geq 0$

In [4]:
leaky_relu = LeakyReLU(alpha=0.01)

In [5]:
leaky_relu = LeakyReLU(alpha=0.01)
x = np.array([0.1, -0.3, 0.5, 0.9, 0, -1.0])
leaky_relu(x)

array([ 0.1  , -0.003,  0.5  ,  0.9  ,  0.   , -0.01 ])

## Ex5.4 c Implement Tanh() activation function (0.5 point)
Implement the __call__ function in ./activations/Tanh.py which takes a tensor x as input and applies the Softmax activation function on x.  
$f(x) = \tanh(x)$

In [6]:
tanh = Tanh()
tanh(x)

array([ 0.09966799, -0.29131261,  0.46211716,  0.71629787,  0.        ,
       -0.76159416])

## Ex5.4 d Implement Softmax() activation function (0.5 point)
Implement the __call__ function in ./activations/Softmax.py which takes a tensor x as input and applies the Softmax activation function on x.

In [7]:
softmax = Softmax()
softmax(x)

array([0.15093442, 0.10117436, 0.22516769, 0.33591072, 0.13657111,
       0.0502417 ])

## Ex5.4 e Implement Sigmoid() activation function (0.5 point)
Implement the __call__ function in ./activations/Sigmoid.py which takes a tensor x as input and applies the Sigmoid activation function on x.

In [8]:
sigmoid = Sigmoid()
sigmoid(x)

array([0.52497919, 0.42555748, 0.62245933, 0.7109495 , 0.5       ,
       0.26894142])

## Ex5.4 f Implement CrossEntropy Loss (0.5 point)
mplement the __call__ function in ./losses/CrossEntropy.py which takes a predictions and true values as agruments and finds the cross entropy loss

In [9]:
ce_loss = CrossEntropy()
predictions = np.array([[0.4,0.35,0.71,0.60],
                        [0.01,0.01,0.01,0.65]])
targets = np.array([[0,0,0,1],
                  [0,0,0,1]])
ce_loss(predictions, targets)

0.47080426832665845

## Ex5.4 g Implement MSE Loss (0.5 point)
Implement the __call__ function in ./losses/MSELoss.py which takes a predictions and true values as agruments and finds the mean squared error loss

In [10]:
mse_loss = MSELoss()
y = np.array([0.6, 0.3, 0.5, 0.1, 1.3, -1.0])
mse_loss(x, y)

0.49000000000000005

## Ex5.4 h Implement Linear() layer (0.5 point)
Implement the __call__ function in ./layers/Linear.py which is y = Wx + b where b is the bias variable. We will do a simple forward pass of with two linear layers and one activation function.

In [12]:
input_data = np.random.randn(20, 100)
layer1 = Linear(100, 20)
layer2 = Linear(20, 10)

h1 = layer1(input_data)
z1 = relu(h1)
h2 = layer2(z1)
z2 = softmax(h2)